// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: v1/user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompanyRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompanyRegisterRequest) Reset() {
	*x = CompanyRegisterRequest{}
	mi := &file_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyRegisterRequest) ProtoMessage() {}

func (x *CompanyRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyRegisterRequest.ProtoReflect.Descriptor instead.
func (*CompanyRegisterRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *CompanyRegisterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CompanyRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CompanyRegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	AppSecret     string                 `protobuf:"bytes,2,opt,name=appSecret,proto3" json:"appSecret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompanyRegisterReply) Reset() {
	*x = CompanyRegisterReply{}
	mi := &file_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyRegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyRegisterReply) ProtoMessage() {}

func (x *CompanyRegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyRegisterReply.ProtoReflect.Descriptor instead.
func (*CompanyRegisterReply) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *CompanyRegisterReply) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CompanyRegisterReply) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

type AccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Sign          string                 `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessTokenRequest) Reset() {
	*x = AccessTokenRequest{}
	mi := &file_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTokenRequest) ProtoMessage() {}

func (x *AccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTokenRequest.ProtoReflect.Descriptor instead.
func (*AccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *AccessTokenRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AccessTokenRequest) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *AccessTokenRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type AccessTokenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessTokenReply) Reset() {
	*x = AccessTokenReply{}
	mi := &file_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessTokenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTokenReply) ProtoMessage() {}

func (x *AccessTokenReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTokenReply.ProtoReflect.Descriptor instead.
func (*AccessTokenReply) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *AccessTokenReply) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type VerifyAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAccessTokenRequest) Reset() {
	*x = VerifyAccessTokenRequest{}
	mi := &file_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAccessTokenRequest) ProtoMessage() {}

func (x *VerifyAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyAccessTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *VerifyAccessTokenRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type VerifyAccessTokenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAccessTokenReply) Reset() {
	*x = VerifyAccessTokenReply{}
	mi := &file_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAccessTokenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAccessTokenReply) ProtoMessage() {}

func (x *VerifyAccessTokenReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAccessTokenReply.ProtoReflect.Descriptor instead.
func (*VerifyAccessTokenReply) Descriptor() ([]byte, []int) {
	return file_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyAccessTokenReply) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyAccessTokenReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_v1_user_proto protoreflect.FileDescriptor

const file_v1_user_proto_rawDesc = "" +
	"\n" +
	"\rv1/user.proto\x12\auser.v1\x1a\x1cgoogle/api/annotations.proto\"B\n" +
	"\x16CompanyRegisterRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"J\n" +
	"\x14CompanyRegisterReply\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1c\n" +
	"\tappSecret\x18\x02 \x01(\tR\tappSecret\"\\\n" +
	"\x12AccessTokenRequest\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x12\n" +
	"\x04sign\x18\x02 \x01(\tR\x04sign\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"4\n" +
	"\x10AccessTokenReply\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\"F\n" +
	"\x18VerifyAccessTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05appId\x18\x02 \x01(\tR\x05appId\"@\n" +
	"\x16VerifyAccessTokenReply\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\xe7\x02\n" +
	"\x04User\x12w\n" +
	"\x0fCompanyRegister\x12\x1f.user.v1.CompanyRegisterRequest\x1a\x1d.user.v1.CompanyRegisterReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/user/v1/company/register\x12f\n" +
	"\vAccessToken\x12\x1b.user.v1.AccessTokenRequest\x1a\x19.user.v1.AccessTokenReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/user/v1/accessToken\x12~\n" +
	"\x11VerifyAccessToken\x12!.user.v1.VerifyAccessTokenRequest\x1a\x1f.user.v1.VerifyAccessTokenReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/user/v1/verifyAccessTokenB\x1cZ\x1akratos-demo/api/user/v1;v1b\x06proto3"

var (
	file_v1_user_proto_rawDescOnce sync.Once
	file_v1_user_proto_rawDescData []byte
)

func file_v1_user_proto_rawDescGZIP() []byte {
	file_v1_user_proto_rawDescOnce.Do(func() {
		file_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_user_proto_rawDesc), len(file_v1_user_proto_rawDesc)))
	})
	return file_v1_user_proto_rawDescData
}

var file_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_user_proto_goTypes = []any{
	(*CompanyRegisterRequest)(nil),   // 0: user.v1.CompanyRegisterRequest
	(*CompanyRegisterReply)(nil),     // 1: user.v1.CompanyRegisterReply
	(*AccessTokenRequest)(nil),       // 2: user.v1.AccessTokenRequest
	(*AccessTokenReply)(nil),         // 3: user.v1.AccessTokenReply
	(*VerifyAccessTokenRequest)(nil), // 4: user.v1.VerifyAccessTokenRequest
	(*VerifyAccessTokenReply)(nil),   // 5: user.v1.VerifyAccessTokenReply
}
var file_v1_user_proto_depIdxs = []int32{
	0, // 0: user.v1.User.CompanyRegister:input_type -> user.v1.CompanyRegisterRequest
	2, // 1: user.v1.User.AccessToken:input_type -> user.v1.AccessTokenRequest
	4, // 2: user.v1.User.VerifyAccessToken:input_type -> user.v1.VerifyAccessTokenRequest
	1, // 3: user.v1.User.CompanyRegister:output_type -> user.v1.CompanyRegisterReply
	3, // 4: user.v1.User.AccessToken:output_type -> user.v1.AccessTokenReply
	5, // 5: user.v1.User.VerifyAccessToken:output_type -> user.v1.VerifyAccessTokenReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_user_proto_init() }
func file_v1_user_proto_init() {
	if File_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_user_proto_rawDesc), len(file_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_user_proto_goTypes,
		DependencyIndexes: file_v1_user_proto_depIdxs,
		MessageInfos:      file_v1_user_proto_msgTypes,
	}.Build()
	File_v1_user_proto = out.File
	file_v1_user_proto_goTypes = nil
	file_v1_user_proto_depIdxs = nil
}
