
version: '3.8'
services:
  mysql_dev:
    image: mysql:8.0
    container_name: mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: DevRoot@1234
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: Dev@5678
      MYSQL_DATABASE: demo
      TZ: Asia/Shanghai
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --bind-address=0.0.0.0
    ports:
      - "33006:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./data/mysql_conf:/etc/mysql/conf.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  mysql_dev_data:
