server:
  http:
    addr: 0.0.0.0:30001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:31001
    timeout: 1s
data:
  database:
    driver: mysql
    source: dev_user:Dev@5678@(127.0.0.1:33006)/demo?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
